### PR TITLE
Update homebrew formulas to gRPC 0.11.0

### PR DESCRIPTION
**Pull request by jtattermusch**
-- bump grpc version
-- bump protobuf version
-- remove dependency on m4 (seems like it was removed from homebrew entirely).

### CODE REVIEW

**Comment by jtattermusch** [comment]
@stanley-cheung  FYI

**Comment by stanley-cheung** [comment]
Let me do some testing tomorrow before merging.

**Comment by tbetbetbe** [comment]
OK, this does not work right now
- there is compile failure compiling the python protobuf extension
- it has actually been fixed google/protobuf#776
- but did not really make it into the last release

Options are
- wait for another protobuf point release
  or
- update the Formula with a [patch](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#patches) of google/protobuf@4472b4ad15827c61d2759776dccadff48a973061

I think we should do the latter. @jtattermusch can you take a look at doing that ?

**Comment by murgatroid99** [comment]
I see the same failure.

**Comment by jtattermusch** [comment]
Added the patch. Can someone verify it now installs correctly?

**Comment by tbetbetbe** [comment]
LGTM:  Compile and install works OK.
@stanley-cheung, @murgatroid99, can either of you confirm and then I'll merge it

**Comment by stanley-cheung** [comment]
I tested this and it installed correctly. Saw these lines during install:

```
==> Patching
patching file python/google/protobuf/pyext/message.cc
```

So I think the patch works.

**Pull request merged**
