### PR TITLE
Corrects python installation instruction

### PR DESCRIPTION
**Pull request by tbetbetbe**

### CODE REVIEW

**Comment by tbetbetbe** [comment]
@jcanizales PTAL

**Comment by jcanizales** [comment]
As you're already here, remove the "if you're Debian/etc." that's inside this Mac section?

**Comment by stanley-cheung** [comment]
LGTM

**Comment by tbetbetbe** [comment]
@jcanizales: I'm doing this from the web ui, so I'll make the other change in a separate PR

**Pull request merged**
