### PR TITLE
Fix fails_with: llvm issue

### PR DESCRIPTION
**Pull request by sdamodharan**

### CODE REVIEW

**Comment by sdamodharan** [comment]
I signed it!

**Comment by marshall-lee** [comment]
👍

**Comment by marshall-lee** [comment]
cc @jtattermusch

**Comment by jtattermusch** [comment]
Can you provide some additional comments on the change? Since when is this ok?

**Comment by marshall-lee** [comment]
@jtattermusch 

https://github.com/Homebrew/homebrew-core/commit/42fc5f72ad4a9932ae5a18e627ba00d61424261d
https://github.com/Homebrew/homebrew-core/pull/7909

**Pull request merged**
