### PR TITLE
Update to release 0.13

### PR DESCRIPTION
**Pull request by stanley-cheung**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Thanks for the change.
Unfortunately, we'll need to do a bit more:

https://github.com/grpc/homebrew-grpc/blob/master/Formula/google-protobuf.rb needs to be updated to beta-2  (otherwise the plugins won't build?)

https://github.com/grpc/homebrew-grpc/blob/master/Formula/grpc.rb#L22   no need to install libgrpc_csharp_ext anymore.

We'll also need to do a pass through the README.md

**Comment by jtattermusch** [comment]
Also, we will need to  check which parts of https://github.com/grpc/homebrew-grpc/blob/master/scripts/install don't make sense anymore.

**Comment by stanley-cheung** [comment]
Agreed with the need to update the install script, especially after we have changed most of each language's installation story. I think we can get these changes in first and then have another issue to track that.

**Comment by jtattermusch** [comment]
Agreed.

**Pull request merged**
