### PR TITLE
Remove protobuf python package from what we're installing

### PR DESCRIPTION
**Pull request by jcanizales**
It was problematic on Linux

### CODE REVIEW

**Comment by jcanizales** [comment]
Ping (before someone else tries following the instructions :)

**Comment by jcanizales** [comment]
@jtattermusch can you take a look?

**Comment by jtattermusch** [comment]
Can you provide more details than just "it was problematic"?

**Comment by jtattermusch** [comment]
Btw, wouldn't --without-python break python because python would then have no protobuf package installed?

**Comment by jcanizales** [comment]
Installation would fail because it expects Python's setuptools module to be already installed. Even if it is installed already, for some reason it still didn't install protoc correctly. Tim told me we actually didn't need the whole section in the google-protobuf formula [from line 79 to 101](https://github.com/grpc/homebrew-grpc/blob/master/Formula/google-protobuf.rb#L79), and we found we could skip it with this flag.

I'm not sure why he thinks so, to be honest. @nathanielmanistaatgoogle, do you know?

For reference, that section of the formula was added in this PR: https://github.com/Homebrew/homebrew/pull/23013

**Comment by nathanielmanistaatgoogle** [comment]
No, I don't happen to know.

**Comment by tbetbetbe** [comment]
grpc-python does not directly depend on an explicit runtime version of protobuf.  Here, it will not require the HEAD version of protobuf that homebrew is installing.
Instead, when grpc-python gets installed, it will pull the released version that it needs from pypi as part of its installation process.

**Comment by jcanizales** [comment]
Merge?

**Pull request merged**
