### PR TITLE
Update homebrew formula to 0.14.0

### PR DESCRIPTION
**Pull request by jtattermusch**
-- update the formula
-- update the documentation and install script to better suit current situation
-- add a workaround for nanopb

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Whoa, I like the part where you removed the wrapped languages from the install script!

**Comment by jtattermusch** [comment]
@stanley-cheung  deleted code is good code.

**Comment by jtattermusch** [comment]
friendly ping.

**Comment by zuyu** [comment]
@jtattermusch How about to upgrade to 0.14.1?

https://github.com/grpc/grpc/releases/tag/release-0_14_1

**Comment by jtattermusch** [comment]
ping again.

**Comment by jtattermusch** [comment]
@zuyu  0.14.1 can be problematic because it depends on unreleased protobuf version. We'll update to 0.14.2. or 0.15.0 soon after this PR goes in.

**Comment by zuyu** [comment]
@jtattermusch ok, and just curious which protobuf version do you refer to?

In this repo, we install protobuf 3.0 beta 2 as the dependency when needed, and there is a newer version ([3.0 beta 3](https://github.com/google/protobuf/releases/tag/v3.0.0-beta-3)) released.

**Comment by jtattermusch** [comment]
@zuyu   3.0.0 beta3 is released now, but it wasn't available for the 0.14.1 release, so we released based on 3.0.0-beta3-pre1.

**Comment by jtattermusch** [comment]
@murgatroid99   ping again.

**Comment by murgatroid99** [comment]
LGTM

**Pull request merged**
